spring:
  datasource:
    url: jdbc:h2:~/greading_db;
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.greading.api: debug
jwt:
  token:
    header: api_key
    issuer: greading
    clientSecret: CLIENT_SECRET
    expirySeconds: 3600