spring:
  datasource:
    url: jdbc:h2:~/greading_db;
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2